schema_version = "1.0.0"

id = "quickref"
version = "1.0.3"
name = "QuickRef"
tagline = "Reference image management"
maintainer = "YLIANG"
type = "add-on"

license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
tags = ["3D View"]

[permissions]
files = "Load reference images selected by the user"
